apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}
            image: stkdio/polkadot-release:latest
            imagePullPolicy: Always
            env:
            - name: TZ
              value: {{ .Values.timezone }}
            - name: PD_API_KEY
              value:  {{ .Values.PAGER_DUTY_API_KEY }}
            - name: SLACK_API
              value: {{ .Values.SLACK_API }}
            - name: SLACK_CHANNEL_NAME
              value: {{ .Values.SLACK_CHANNEL_NAME }}
          imagePullSecrets: 
            - name: registry-credentials
          restartPolicy: OnFailure
