apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}
            image: stkdio/github-release-notifications:1.0.18
            imagePullPolicy: Always
            env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: PD_API_KEY
              value: {{ .Values.PAGER_DUTY_API_KEY | quote }}
            - name: SLACK_API
              value: {{ .Values.SLACK_API | quote }}
            - name: SLACK_CHANNEL_NAME
              value: {{ .Values.SLACK_CHANNEL_NAME | quote }}
            - name: GITHUB_API
              value: {{ .Values.GITHUB_API_TOKEN | quote }}
            - name: GITHUB_REPO
              value: {{ .Values.GITHUB_REPO | quote }}
            - name: CHECK_TIMER
              value: {{ .Values.CHECK_TIMER | quote }}
          restartPolicy: OnFailure
